### ISSUE TITLE
Unable to use ColouredTriMeshViewer3d

### ISSUE THREAD

**Issue by chaoweifang** [menpo/menpo3d#50]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cwfang/.local/lib/python2.7/site-packages/menpo3d/visualize/viewmayavi.py", line 439, in render
    specular_light=specular_light, alpha=alpha)
  File "/home/cwfang/.local/lib/python2.7/site-packages/menpo3d/visualize/viewmayavi.py", line 420, in _render_mesh
    mapper.set_input_data(pd)
AttributeError: 'PolyDataMapper' object has no attribute 'set_input_data'

**Comment by patricksnape** [comment]
This is an issue with VTK - which version of VTK do you have installed?
